### ISSUE TITLE
How to  get Client credentials(client id  and  secret key ) 

### ISSUE THREAD

**Issue by arbeeorlar** [techquest/isw-payment-sdk-android#24]
Hi Interswitch , How  do  i generate  client  id  and  secret  key  for  the  SDK.

Thanks

**Comment by Emmarock** [comment]
To use the SDK, you have to register as a merchant, after your registration you will get your clientId and secret

**Comment by litunny** [comment]
@arbeeorlar , you should get both keys from your interswitch console.
